controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

controllers_marketing:
    resource: '../src/BoundedContexts/Marketing/Infrastructure/Symfony/Adapters/PrimaryIn/Controller/'
    type: annotation
    prefix: /marketing